# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(322927)
$foreground = rgb(FDEFBF)
$color0 = rgb(574E4C)
$color1 = rgb(3A1E1A)
$color2 = rgb(5E4D4B)
$color3 = rgb(AC3F19)
$color4 = rgb(7C7575)
$color5 = rgb(868382)
$color6 = rgb(BB9C35)
$color7 = rgb(F4DF9A)
$color8 = rgb(AB9C6C)
$color9 = rgb(4E2823)
$color10 = rgb(7D6764)
$color11 = rgb(E65422)
$color12 = rgb(A59C9B)
$color13 = rgb(B3AEAE)
$color14 = rgb(FAD047)
$color15 = rgb(F4DF9A)
