#exec-once = $HOME/.my_scripts/refresh_networks.sh
#exec-once = wasistlos
exec-once = $HOME/.config/hypr/custom/startup.sh

# 3-finger swipe down to focus the next window
gesture = 3, down, dispatcher, cyclenext
# 3-finger swipe up to focus the previous window
gesture = 3, up, dispatcher, cyclenext, prev

# Match your card IDs: Intel (card1) is primary, NVIDIA (card0) is secondary
env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0
env = WLR_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0

# Force standard toolkit to ignore NVIDIA
env = __GLX_VENDOR_LIBRARY_NAME,mesa
env = LIBVA_DRIVER_NAME,iHD
# Explicitly force the Intel Render Node
env = WLR_DRM_DEVICES,/dev/dri/card1
env = AQ_DRM_DEVICES,/dev/dri/card1

xwayland {
  force_zero_scaling = true
}
env = XWAYLAND_NO_GLAMOR,1

